name: flutter_clean_architecture
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.3.5
  get_it: ^7.6.0
  go_router: ^9.0.0
  google_fonts: ^4.0.4
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  video_player: ^2.7.0
  


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - assets/icons/

  # fonts:
  #   - family: Satoshi
  #     fonts:
  #       - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
  #       - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
  #       - asset: assets/fonts/Satoshi/Satoshi-Bold.otf